### ISSUE TITLE
Mod Not Working

### ISSUE THREAD

**Issue by dewast** [JDOGG88/Logistic-Machines#1]
{
  "mods": 
  [
    
    {
      "name": "base",
      "enabled": true
    },
    
    {
      "name": "aai-programmable-vehicles",
      "enabled": true
    },
    
    {
      "name": "aai-signals",
      "enabled": false
    },
    
    {
      "name": "Aircraft",
      "enabled": true
    },
    
    {
      "name": "AtomicRobotsFixv",
      "enabled": false
    },
    
    {
      "name": "auto-research-redistributed",
      "enabled": false
    },
    
    {
      "name": "BetterBots",
      "enabled": true
    },
    
    {
      "name": "boblibrary",
      "enabled": true
    },
    
    {
      "name": "bobvehicleequipment",
      "enabled": true
    },
    
    {
      "name": "Factorissimo2",
      "enabled": true
    },
    
    {
      "name": "FlyingRoboport",
      "enabled": true
    },
    
    {
      "name": "gas-generator",
      "enabled": true
    },
    
    {
      "name": "Hover-Car",
      "enabled": true
    },
    
    {
      "name": "ItemTeleportation",
      "enabled": false
    },
    
    {
      "name": "Krastorio2",
      "enabled": false
    },
    
    {
      "name": "KS_Power",
      "enabled": true
    },
    
    {
      "name": "Load-Furn",
      "enabled": true
    },
    
    {
      "name": "Logistic-Machines",
      "enabled": true
    },
    
    {
      "name": "Mining_Drones",
      "enabled": true
    },
    
    {
      "name": "Mobile_Factory",
      "enabled": false
    },
    
    {
      "name": "Mobile_Factory_Graphics",
      "enabled": true
    },
    
    {
      "name": "NuclearRobots_Reboot",
      "enabled": true
    },
    
    {
      "name": "RoboportMK2",
      "enabled": true
    },
    
    {
      "name": "robotarmy",
      "enabled": true
    },
    
    {
      "name": "robotworld-continued",
      "enabled": true
    },
    
    {
      "name": "skan-fusion-robots",
      "enabled": true
    },
    
    {
      "name": "Turret-Shields",
      "enabled": true
    },
    
    {
      "name": "uniturret",
      "enabled": true
    },
    
    {
      "name": "Vehicle-turrets",
      "enabled": true
    },
    
    {
      "name": "WideChests",
      "enabled": true
    }
  ]
}

**Comment by JDOGG88** [comment]
This issue has been resolved with v0.18.4.
